name: Test Secrets

on: push

jobs:
  secrets:
    runs-on: ubuntu-latest

    env:
      MY_VAR: ${{ secrets.MY_SECRET }}

    steps:
      - name: Print secret
        run: |
          import os
          print(len(os.getenv('MY_VAR')))
        shell : python
